
services:
  postgresdb:
    image: postgres:16
    restart: unless-stopped
    env_file: ./.env
    healthcheck: 
     test: pg_isready || exit 1
     interval: 5s
     timeout: 10s
     retries: 3
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  liquibase:
    image: liquibase/liquibase:4.9.1
    container_name: liquibase
    depends_on:
      postgresdb:
        condition: service_healthy
    command: --url=jdbc:postgresql://postgresdb:5432/postgres?user=$POSTGRESDB_USER&password=$POSTGRESDB_PASSWORD --changeLogFile=/liquibase/changelog/changelog.yaml update
  app:
    depends_on:
      - postgresdb
      - liquibase
    build: .
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE",
        "spring.datasource.username" : "$POSTGRESDB_USER",
        "spring.datasource.password" : "$POSTGRESDB_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
