#spring:
#  liquibase:
#    enabled: false
#  application:
#    name: postgres
#  datasource:
#    url: jdbc:postgresql://localhost:5433/accounting
#    username: postgres
#    password: NeronKid
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true